development:
  adapter: postgresql
  encoding: unicode
  host: 172.25.137.160
  database: danieloliveira
  pool: 5
  username: danieloliveira
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  host: 172.25.137.160
  database: danieloliveira
  pool: 5
  username: danieloliveira
  password: 123456
